// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_4668a8c0df8f6333, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type User struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	About                string   `protobuf:"bytes,5,opt,name=About,proto3" json:"About,omitempty"`
	Avatar               string   `protobuf:"bytes,6,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,7,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	Address              string   `protobuf:"bytes,8,opt,name=Address,proto3" json:"Address,omitempty"`
	City                 string   `protobuf:"bytes,9,opt,name=City,proto3" json:"City,omitempty"`
	Country              string   `protobuf:"bytes,10,opt,name=Country,proto3" json:"Country,omitempty"`
	Gender               string   `protobuf:"bytes,11,opt,name=Gender,proto3" json:"Gender,omitempty"`
	PostCode             string   `protobuf:"bytes,12,opt,name=PostCode,proto3" json:"PostCode,omitempty"`
	Birthday             string   `protobuf:"bytes,13,opt,name=Birthday,proto3" json:"Birthday,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_4668a8c0df8f6333, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetAbout() string {
	if m != nil {
		return m.About
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *User) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *User) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *User) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *User) GetPostCode() string {
	if m != nil {
		return m.PostCode
	}
	return ""
}

func (m *User) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*User)(nil), "User")
}

func init() {
	proto.RegisterFile("protos/auth.proto", fileDescriptor_4668a8c0df8f6333)
}

var fileDescriptor_4668a8c0df8f6333 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xc1, 0x4a, 0xfb, 0x40,
	0x10, 0xc6, 0x69, 0xff, 0x69, 0xda, 0x4e, 0xfb, 0x17, 0x5c, 0x44, 0x86, 0xa2, 0x50, 0x7a, 0xf2,
	0x94, 0x82, 0x3e, 0x41, 0x1a, 0xd4, 0x8b, 0x94, 0x52, 0xf0, 0xe2, 0x6d, 0xe3, 0x2e, 0x66, 0xc1,
	0x64, 0xcb, 0xee, 0x44, 0xc9, 0xab, 0xfa, 0x34, 0xb2, 0xb3, 0x89, 0x7a, 0xca, 0xfc, 0xbe, 0x6f,
	0xbe, 0x30, 0xb3, 0x03, 0xe7, 0x27, 0x67, 0xc9, 0xfa, 0xad, 0x6c, 0xa9, 0xca, 0xb8, 0xde, 0x4c,
	0x61, 0x72, 0x5f, 0x9f, 0xa8, 0xdb, 0x7c, 0x8d, 0x21, 0x79, 0xf6, 0xda, 0x89, 0x2b, 0x98, 0x3f,
	0x18, 0xe7, 0x69, 0x2f, 0x6b, 0x8d, 0xa3, 0xf5, 0xe8, 0x66, 0x7e, 0xfc, 0x15, 0xc4, 0x0a, 0x66,
	0x4f, 0xb2, 0x37, 0xc7, 0x6c, 0xfe, 0xb0, 0xb8, 0x08, 0xff, 0x92, 0xe6, 0x1d, 0xff, 0xb1, 0x11,
	0x21, 0x24, 0x0e, 0xd2, 0xfb, 0x4f, 0xeb, 0x14, 0x26, 0x31, 0x31, 0x70, 0x48, 0xe4, 0xa5, 0x6d,
	0x09, 0x27, 0x31, 0xc1, 0x20, 0x2e, 0x21, 0xcd, 0x3f, 0x24, 0x49, 0x87, 0x29, 0xcb, 0x3d, 0x89,
	0x35, 0x2c, 0x0e, 0x95, 0x6d, 0xf4, 0xbe, 0xad, 0x4b, 0xed, 0x70, 0xca, 0xe6, 0x5f, 0x49, 0x20,
	0x4c, 0x73, 0xa5, 0x9c, 0xf6, 0x1e, 0x67, 0xec, 0x0e, 0x28, 0x04, 0x24, 0x85, 0xa1, 0x0e, 0xe7,
	0x2c, 0x73, 0x1d, 0xba, 0x0b, 0xdb, 0x36, 0xe4, 0x3a, 0x84, 0xd8, 0xdd, 0x63, 0x98, 0xe0, 0x51,
	0x37, 0x4a, 0x3b, 0x5c, 0xc4, 0x09, 0x22, 0xf1, 0x2e, 0xd6, 0x53, 0x61, 0x95, 0xc6, 0x65, 0xbf,
	0x4b, 0xcf, 0xc1, 0xdb, 0x19, 0x47, 0x95, 0x92, 0x1d, 0xfe, 0x8f, 0xde, 0xc0, 0xb7, 0x5b, 0x38,
	0xcb, 0x5b, 0xaa, 0x74, 0x43, 0xe6, 0x55, 0x92, 0xb1, 0x8d, 0xb8, 0x86, 0xe5, 0x51, 0xbf, 0x19,
	0x4f, 0xda, 0xf1, 0xab, 0x4f, 0xb2, 0xf0, 0x59, 0xa5, 0x19, 0x5f, 0x63, 0x97, 0xbe, 0x24, 0xe1,
	0x48, 0x65, 0xca, 0x57, 0xba, 0xfb, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x19, 0x11, 0xaf, 0xba,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthenticationClient is the client API for Authentication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticationClient interface {
	RegisterUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*Empty, error)
}

type authenticationClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticationClient(cc grpc.ClientConnInterface) AuthenticationClient {
	return &authenticationClient{cc}
}

func (c *authenticationClient) RegisterUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Authentication/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationServer is the server API for Authentication service.
type AuthenticationServer interface {
	RegisterUser(context.Context, *User) (*Empty, error)
}

// UnimplementedAuthenticationServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticationServer struct {
}

func (*UnimplementedAuthenticationServer) RegisterUser(ctx context.Context, req *User) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}

func RegisterAuthenticationServer(s *grpc.Server, srv AuthenticationServer) {
	s.RegisterService(&_Authentication_serviceDesc, srv)
}

func _Authentication_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Authentication/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).RegisterUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authentication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Authentication",
	HandlerType: (*AuthenticationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _Authentication_RegisterUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/auth.proto",
}
