// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2023-06-04 20:48:38.098497808 -0300 -03 m=+0.254476976

package docs

import (
	"bytes"
	"encoding/json"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "This is PowerSSO app server.",
        "title": "Documentation PowerSSO",
        "contact": {
            "name": "PowerSSO",
            "url": "https://github.com/isaqueveras/powersso/issues"
        },
        "license": {
            "name": "MIT license",
            "url": "https://github.com/isaqueveras/powersso/blob/main/LICENSE"
        },
        "version": "1.0.0"
    },
    "host": "localhost:5000",
    "basePath": "/",
    "paths": {
        "/v1/auth/activation/{token}": {
            "post": {
                "description": "Route to activate the user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Http/Auth"
                ],
                "summary": "Activate the user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/utils.NoContent"
                        }
                    }
                }
            }
        },
        "/v1/auth/login": {
            "post": {
                "description": "Route to login a user account into the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Http/Auth"
                ],
                "summary": "User login",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/auth.Session"
                        }
                    }
                }
            }
        },
        "/v1/auth/login/steps": {
            "get": {
                "description": "Steps to login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Http/Auth"
                ],
                "summary": "Steps to login",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/auth.Steps"
                        }
                    }
                }
            }
        },
        "/v1/auth/logout": {
            "delete": {
                "description": "Route to logout a user account into the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Http/Auth"
                ],
                "summary": "User logout",
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/utils.NoContent"
                        }
                    }
                }
            }
        },
        "/v1/auth/register": {
            "post": {
                "description": "Register a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Http/Auth"
                ],
                "summary": "Register a user",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/utils.NoContent"
                        }
                    }
                }
            }
        },
        "/v1/auth/user/{user_uuid}/disable": {
            "put": {
                "description": "Route to disable a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Http/Auth/User"
                ],
                "summary": "Disable user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID of the user",
                        "name": "user_uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/utils.NoContent"
                        }
                    }
                }
            }
        },
        "/v1/auth/user/{user_uuid}/otp/configure": {
            "post": {
                "description": "Configure a user's OTP",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Http/Auth/OTP"
                ],
                "summary": "Configure a user's OTP",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/utils.NoContent"
                        }
                    }
                }
            }
        },
        "/v1/auth/user/{user_uuid}/otp/qrcode": {
            "get": {
                "description": "Configure a user's OTP",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Http/Auth/OTP"
                ],
                "summary": "Configure a user's OTP",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/auth.QRCode"
                        }
                    }
                }
            }
        },
        "/v1/auth/user/{user_uuid}/otp/unconfigure": {
            "put": {
                "description": "unconfigure a user's OTP",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Http/Auth/OTP"
                ],
                "summary": "unconfigure a user's OTP",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/utils.NoContent"
                        }
                    }
                }
            }
        },
        "/v1/project/create": {
            "post": {
                "description": "Register a project including several users to the project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Http/Project"
                ],
                "summary": "Register a projet",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/utils.NoContent"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.QRCode": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "auth.Session": {
            "type": "object",
            "properties": {
                "about": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "data": {
                    "type": "object"
                },
                "email": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "level": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "auth.Steps": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "otp": {
                    "type": "boolean"
                }
            }
        },
        "utils.NoContent": {
            "type": "object"
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{ Schemes: []string{}}

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface {}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
